services:
  keycloak-db:
    image: postgres:13
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: user_keycloak
      POSTGRES_PASSWORD: user_keycloak_password
    ports:
      - "5500:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "keycloak" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    restart: always
    volumes:
      - D:/opt/keycloak-db/data:/var/lib/postgresql/data
      - ./keycloak/sql/init-schema.sql:/docker-entrypoint-initdb.d/init-schema.sql
    networks:
      - keycloak-network
  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    container_name: keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak
      DB_SCHEMA: keycloak
      DB_USER: user_keycloak
      DB_PASSWORD: user_keycloak_password
    restart: on-failure:20
    depends_on:
      keycloak-db:
        condition: service_healthy
    ports:
      - "5501:8080"
    volumes:
      - D:/opt/keycloak/data:/opt/keycloak/data
    networks:
      - keycloak-network
networks:
  keycloak-network:
    name: keycloak-network
    driver: bridge
