version: '3.9'
services:
  keycloak-db:
    image: postgres:13
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: user_keycloak
      POSTGRES_PASSWORD: user_keycloak_password
    ports:
      - "5500:5432"
    volumes:
      - D:/opt/keycloak-db/data:/var/lib/postgresql/data
    networks:
      - keycloak-network
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak
      DB_USER: user_keycloak
      DB_PASSWORD: user_keycloak_password
    ports:
      - "5501:8080"
    networks:
      - keycloak-network
networks:
  keycloak-network:
    name: keycloak-network
    driver: bridge
